%% run_full_build.m
% Master script: runs the complete Simulink model build pipeline.
%
% OVERVIEW
%   This script builds a complete Simulink model for a 5-tank Fuel Quantity
%   Indication System (FQIS) with capacitance probes, probe failure detection,
%   3-D height-volume lookup tables, dielectric-to-density conversion, and a
%   single-point refuel system with high-level shutoff valves.
%
% PIPELINE
%   Step 1: Project setup — create directories and an empty data dictionary
%   Step 2: Populate data dictionary — buses, parameters, tank structs, 3-D LUTs
%   Step 3: Build Simulink models — 12 .slx files with model references
%   Step 4: Validate — 50 automated checks (file existence, dict entries, LUT
%           dimensions, monotonicity, and model loadability)
%
% ARCHITECTURE
%   The top-level model (FuelGaugingSystem.slx) references sub-models for each
%   functional block. All parameters come from the data dictionary — nothing
%   is hard-coded in the base workspace. The per-tank processing chain is:
%
%     FuelWL --> ProbeModel_{Real|Combo|Pseudo}   Convert fuel surface to probe height
%           --> ProbeFailureDetector               Open/short/rate fault detection + LKG hold
%           --> HV_TableLookup_T{1-5}              3-D n-D interpolation (height x pitch x roll)
%           --> Gain (1/231)                       Cubic inches to US gallons
%           --> Product (gallons x density)         Final weight per tank
%
%   Density is computed once from the dielectric constant:
%     Dielectric --> DensityComputation --> density (shared across all tanks)
%
%   The refuel system monitors fuel waterlines and controls shutoff valves:
%     FuelWL_T{1-5} + Refuel_Cmd --> RefuelSystem --> valve/sensor status
%
% DESIGN DECISIONS
%   - Per-tank HV lookup models: Simulink n-D Lookup Table objects cannot be
%     parameterized by name at runtime, so each tank gets its own .slx file
%     (HV_TableLookup_T1 through T5) wired to its specific LUT object.
%
%   - Model workspace variables (not model arguments): The ParameterArgumentNames
%     API requires variables to already exist in the model workspace before they
%     can be declared as arguments. We use assignin(mdlWorkspace, ...) to set
%     default values that can be overridden by the parent model.
%
%   - Homogeneous TankParams struct: MATLAB struct arrays require all elements
%     to have the same fields. Tanks without combo probes use NaN for the
%     lower_base/lower_top/upper_base/upper_top fields.
%
%   - Data dictionary filename: set_param(..., 'DataDictionary') takes just the
%     filename (e.g., 'FuelGaugingData.sldd'), not the full path. The directory
%     containing the .sldd must be on the MATLAB path.
%
% PREREQUISITES
%   - MATLAB R2024b+ with Simulink
%   - H-V table data in data/tank_system.mat (generated by Python pipeline or
%     generate_hv_tables.m). This file contains cell arrays of height and volume
%     vectors for all 5 tanks across 13 pitch x 17 roll attitude combinations.
%
% USAGE
%   >> cd synthetic_fuel_system/matlab/scripts
%   >> run_full_build
%
% See also: build_data_dictionary.m, build_simulink_model.m, validate_model.m

clear; clc; close all;
fprintf('================================================================\n');
fprintf('  FUEL GAUGING SYSTEM — FULL SIMULINK BUILD\n');
fprintf('================================================================\n\n');

%% Path configuration
script_dir = fileparts(mfilename('fullpath'));
matlab_dir = fileparts(script_dir);
root_dir   = fileparts(matlab_dir);
data_dir   = fullfile(root_dir, 'data');
model_dir  = fullfile(matlab_dir, 'models');
dd_dir     = fullfile(matlab_dir, 'data');

fprintf('Root:    %s\n', root_dir);
fprintf('MATLAB:  %s\n', matlab_dir);
fprintf('Models:  %s\n', model_dir);
fprintf('Data:    %s\n\n', data_dir);

%% ========================================================================
%  STEP 1: PROJECT SETUP
%  ========================================================================

fprintf('================================================================\n');
fprintf('  STEP 1: PROJECT SETUP\n');
fprintf('================================================================\n\n');

% Create directories
dirs_to_create = {model_dir, dd_dir, ...
    fullfile(matlab_dir, 'work'), ...
    fullfile(matlab_dir, 'tests'), ...
    fullfile(matlab_dir, 'utilities')};
for i = 1:numel(dirs_to_create)
    if ~exist(dirs_to_create{i}, 'dir')
        mkdir(dirs_to_create{i});
        fprintf('  Created: %s\n', dirs_to_create{i});
    end
end

% Add model directory to path so model references resolve
addpath(model_dir);

% Create data dictionary if it doesn't exist
dd_path = fullfile(dd_dir, 'FuelGaugingData.sldd');
if ~exist(dd_path, 'file')
    dd = Simulink.data.dictionary.create(dd_path);
    saveChanges(dd);
    close(dd);
    fprintf('  Created data dictionary: %s\n', dd_path);
else
    fprintf('  Data dictionary exists: %s\n', dd_path);
end

fprintf('\n  Step 1 complete.\n\n');

%% ========================================================================
%  STEP 2: POPULATE DATA DICTIONARY
%  ========================================================================

fprintf('================================================================\n');
fprintf('  STEP 2: POPULATE DATA DICTIONARY\n');
fprintf('================================================================\n\n');

dd = Simulink.data.dictionary.open(dd_path);
ddata = getSection(dd, 'Design Data');

% ---------- 2a. Bus Definitions ----------
fprintf('--- Creating Bus Definitions ---\n');

% AttitudeBus
elems = [];
e = Simulink.BusElement; e.Name = 'pitch_deg'; e.DataType = 'double';
e.Unit = 'deg'; e.Description = 'Aircraft pitch angle';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'roll_deg'; e.DataType = 'double';
e.Unit = 'deg'; e.Description = 'Aircraft roll angle';
elems = [elems; e];
bus = Simulink.Bus;
bus.Description = 'Aircraft attitude';
bus.Elements = elems;
addOrUpdateDD(ddata, 'AttitudeBus', bus);
fprintf('  AttitudeBus\n');

% ProbeReadingBus
elems = [];
e = Simulink.BusElement; e.Name = 'probe_height'; e.DataType = 'double';
e.Unit = 'in'; e.Description = 'Wetted height on probe';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'fuel_wl'; e.DataType = 'double';
e.Unit = 'in'; e.Description = 'Fuel surface waterline at probe';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'is_valid'; e.DataType = 'boolean';
e.Description = 'True if reading passed health checks';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'failure_code'; e.DataType = 'uint8';
e.Description = '0=OK, 1=OpenCkt, 2=ShortCkt, 3=RateExceed, 4=Stale';
elems = [elems; e];
bus = Simulink.Bus;
bus.Description = 'Single probe measurement output';
bus.Elements = elems;
addOrUpdateDD(ddata, 'ProbeReadingBus', bus);
fprintf('  ProbeReadingBus\n');

% BIT_StatusBus
elems = [];
e = Simulink.BusElement; e.Name = 'all_probes_healthy'; e.DataType = 'boolean';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'num_failed_probes'; e.DataType = 'uint8';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'failure_flags'; e.DataType = 'boolean';
e.Dimensions = 5;
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'failure_codes'; e.DataType = 'uint8';
e.Dimensions = 5;
elems = [elems; e];
bus = Simulink.Bus;
bus.Description = 'Built-in test status for all probes';
bus.Elements = elems;
addOrUpdateDD(ddata, 'BIT_StatusBus', bus);
fprintf('  BIT_StatusBus\n');

% TankIndicationBus
elems = [];
e = Simulink.BusElement; e.Name = 'volume_in3'; e.DataType = 'double';
e.Unit = 'in^3';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'volume_gal'; e.DataType = 'double';
e.Unit = 'gal';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'weight_lb'; e.DataType = 'double';
e.Unit = 'lb';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'probe_data'; e.DataType = 'Bus: ProbeReadingBus';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'tank_id'; e.DataType = 'uint8';
elems = [elems; e];
bus = Simulink.Bus;
bus.Description = 'Per-tank fuel quantity indication';
bus.Elements = elems;
addOrUpdateDD(ddata, 'TankIndicationBus', bus);
fprintf('  TankIndicationBus\n');

% SystemIndicationBus
elems = [];
e = Simulink.BusElement; e.Name = 'total_weight_lb'; e.DataType = 'double';
e.Unit = 'lb';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'total_volume_gal'; e.DataType = 'double';
e.Unit = 'gal';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'density_system'; e.DataType = 'double';
e.Unit = 'lb/gal';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'bit_status';
e.DataType = 'Bus: BIT_StatusBus';
elems = [elems; e];
bus = Simulink.Bus;
bus.Description = 'Complete system fuel quantity indication';
bus.Elements = elems;
addOrUpdateDD(ddata, 'SystemIndicationBus', bus);
fprintf('  SystemIndicationBus\n');

% RefuelStatusBus
elems = [];
e = Simulink.BusElement; e.Name = 'is_active'; e.DataType = 'boolean';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'is_complete'; e.DataType = 'boolean';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'valve_positions'; e.DataType = 'double';
e.Dimensions = 5;
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'hi_level_states'; e.DataType = 'boolean';
e.Dimensions = 5;
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'flow_rates_gpm'; e.DataType = 'double';
e.Dimensions = 5; e.Unit = 'gal/min';
elems = [elems; e];
e = Simulink.BusElement; e.Name = 'total_delivered_gal'; e.DataType = 'double';
e.Unit = 'gal';
elems = [elems; e];
bus = Simulink.Bus;
bus.Description = 'Single-point refuel system status';
bus.Elements = elems;
addOrUpdateDD(ddata, 'RefuelStatusBus', bus);
fprintf('  RefuelStatusBus\n');

% ---------- 2b. System Parameters ----------
fprintf('\n--- Creating System Parameters ---\n');

params = {
    'IN3_PER_GAL',             231.0,   'in^3/gal', 'Cubic inches per US gallon'
    'ULLAGE_FRAC',             0.02,    '',         'Ullage expansion reserve fraction'
    'UNUSABLE_FRAC',           0.015,   '',         'Unusable fuel fraction'
    'DENSITY_MODEL_A',         4.667,   'lb/(gal)', 'Density model slope'
    'DENSITY_MODEL_B',         -2.857,  'lb/gal',   'Density model intercept'
    'DENSITY_BIAS',            1.003,   '',         'Density bias multiplier (0.3% high)'
    'KAPPA_NOMINAL',           2.05,    '',         'Nominal fuel dielectric constant'
    'DENSITY_LAB',             6.71,    'lb/gal',   'Lab-measured fuel density'
    'PROBE_NOISE_STD',         0.02,    'in',       'Probe measurement noise sigma'
    'SUPPLY_PRESSURE_PSI',     55.0,    'psi',      'Refuel supply pressure'
    'MANIFOLD_WL',             78.0,    'in',       'Refuel manifold waterline'
    'MAX_FLOW_GPM',            60.0,    'gal/min',  'Max total refuel flow rate'
    'VALVE_CAPACITY_GPM',      15.0,    'gal/min',  'Per-valve max flow rate'
    'VALVE_CLOSE_TIME',        0.5,     's',        'Shutoff valve close time'
    'VALVE_OPEN_TIME',         0.3,     's',        'Shutoff valve open time'
    'FAILURE_OPEN_THRESH',     -0.1,    'in',       'Open circuit threshold'
    'FAILURE_SHORT_MARGIN',    0.5,     'in',       'Short circuit margin above max'
    'FAILURE_RATE_THRESH',     2.0,     'in/s',     'Rate exceedance threshold'
    'FAILURE_STALE_TIMEOUT',   30.0,    's',        'Stale data timeout'
    'FAILURE_STALE_DELTA',     0.01,    'in',       'Stale data minimum change'
    'BLEND_LO_WL',             90.0,    'in',       'T3 blend zone lower bound'
    'BLEND_HI_WL',             92.0,    'in',       'T3 blend zone upper bound'
    'PSEUDO_DX',               55.0,    'in',       'T5 pseudo FS offset from T3'
    'PSEUDO_DY',               0.0,     'in',       'T5 pseudo BL offset from T3'
};

for i = 1:size(params, 1)
    p = Simulink.Parameter;
    p.Value = params{i, 2};
    p.DataType = 'double';
    p.Unit = params{i, 3};
    p.Description = params{i, 4};
    p.CoderInfo.StorageClass = 'Auto';
    addOrUpdateDD(ddata, params{i, 1}, p);
end
fprintf('  Created %d parameters\n', size(params, 1));

% ---------- 2c. Tank Parameter Structures ----------
fprintf('\n--- Creating Tank Parameter Structures ---\n');

TankParams = struct();

% All tanks must have identical fields for struct array homogeneity.
% Tanks without combo probes use NaN for lower/upper fields.
TankParams(1).name       = 'Forward';
TankParams(1).tank_id    = uint8(1);
TankParams(1).fs_min     = 195.0;  TankParams(1).fs_max     = 225.0;
TankParams(1).bl_min     = -15.0;  TankParams(1).bl_max     = 15.0;
TankParams(1).wl_min     = 88.0;   TankParams(1).wl_max     = 104.0;
TankParams(1).base_area  = 900.0;
TankParams(1).height     = 16.0;
TankParams(1).probe_base = 88.24;  TankParams(1).probe_top  = 103.68;
TankParams(1).lower_base = NaN;    TankParams(1).lower_top  = NaN;
TankParams(1).upper_base = NaN;    TankParams(1).upper_top  = NaN;
TankParams(1).max_fill   = 103.68;
TankParams(1).probe_type = uint8(1);

TankParams(2).name       = 'Left';
TankParams(2).tank_id    = uint8(2);
TankParams(2).fs_min     = 235.0;  TankParams(2).fs_max     = 285.0;
TankParams(2).bl_min     = -62.0;  TankParams(2).bl_max     = -22.0;
TankParams(2).wl_min     = 85.0;   TankParams(2).wl_max     = 103.0;
TankParams(2).base_area  = 2000.0;
TankParams(2).height     = 18.0;
TankParams(2).probe_base = 85.27;  TankParams(2).probe_top  = 102.64;
TankParams(2).lower_base = NaN;    TankParams(2).lower_top  = NaN;
TankParams(2).upper_base = NaN;    TankParams(2).upper_top  = NaN;
TankParams(2).max_fill   = 102.64;
TankParams(2).probe_type = uint8(1);

TankParams(3).name       = 'Center';
TankParams(3).tank_id    = uint8(3);
TankParams(3).fs_min     = 235.0;  TankParams(3).fs_max     = 285.0;
TankParams(3).bl_min     = -20.0;  TankParams(3).bl_max     = 20.0;
TankParams(3).wl_min     = 80.0;   TankParams(3).wl_max     = 100.0;
TankParams(3).base_area  = 2000.0;
TankParams(3).height     = 20.0;
TankParams(3).probe_base = 80.30;  TankParams(3).probe_top  = 99.60;
TankParams(3).lower_base = 80.30;  TankParams(3).lower_top  = 92.00;
TankParams(3).upper_base = 90.00;  TankParams(3).upper_top  = 99.60;
TankParams(3).max_fill   = 99.60;
TankParams(3).probe_type = uint8(2);

TankParams(4).name       = 'Right';
TankParams(4).tank_id    = uint8(4);
TankParams(4).fs_min     = 235.0;  TankParams(4).fs_max     = 285.0;
TankParams(4).bl_min     = 22.0;   TankParams(4).bl_max     = 62.0;
TankParams(4).wl_min     = 85.0;   TankParams(4).wl_max     = 103.0;
TankParams(4).base_area  = 2000.0;
TankParams(4).height     = 18.0;
TankParams(4).probe_base = 85.27;  TankParams(4).probe_top  = 102.64;
TankParams(4).lower_base = NaN;    TankParams(4).lower_top  = NaN;
TankParams(4).upper_base = NaN;    TankParams(4).upper_top  = NaN;
TankParams(4).max_fill   = 102.64;
TankParams(4).probe_type = uint8(1);

TankParams(5).name       = 'Aft';
TankParams(5).tank_id    = uint8(5);
TankParams(5).fs_min     = 295.0;  TankParams(5).fs_max     = 335.0;
TankParams(5).bl_min     = -17.5;  TankParams(5).bl_max     = 17.5;
TankParams(5).wl_min     = 83.0;   TankParams(5).wl_max     = 105.0;
TankParams(5).base_area  = 1400.0;
TankParams(5).height     = 22.0;
TankParams(5).probe_base = 83.0;   TankParams(5).probe_top  = 105.0;
TankParams(5).lower_base = NaN;    TankParams(5).lower_top  = NaN;
TankParams(5).upper_base = NaN;    TankParams(5).upper_top  = NaN;
TankParams(5).max_fill   = 104.56;
TankParams(5).probe_type = uint8(3);

tp = Simulink.Parameter;
tp.Value = TankParams;
tp.Description = 'Per-tank geometric and probe parameters (1x5 struct array)';
addOrUpdateDD(ddata, 'TankParams', tp);
fprintf('  Created TankParams (5 tanks)\n');

% ---------- 2d. Lookup Table Objects ----------
% Load the Python-generated H-V tables and convert them into Simulink
% LookupTable objects for use by the n-D Lookup Table blocks.
%
% The source .mat file contains cell arrays where each cell holds a
% variable-length vector (different heights have slightly different
% point counts at extreme attitudes). We must:
%   1. Pick a common height breakpoint grid (from the level-attitude table)
%   2. Interpolate all attitude tables onto this common grid
%   3. Enforce monotonicity (volume must not decrease with height)
%   4. Clamp negative volumes to zero
%   5. Package into a Simulink.LookupTable with 3 breakpoint dimensions
%
% The resulting LUT objects are stored in the data dictionary and
% referenced by name from the HV_TableLookup_T{n}.slx models.
fprintf('\n--- Creating Lookup Table Objects ---\n');

hv_file = fullfile(data_dir, 'tank_system.mat');
if ~exist(hv_file, 'file')
    error('H-V table data not found: %s\nRun the Python pipeline first.', hv_file);
end

hv_data = load(hv_file);
fprintf('  Loaded H-V data from: %s\n', hv_file);

pitch_bp = hv_data.pitch_range(:)';
roll_bp  = hv_data.roll_range(:)';

for t = 1:5
    prefix = sprintf('T%d', t);
    heights_cell = hv_data.([prefix '_heights']);
    volumes_cell = hv_data.([prefix '_volumes']);

    n_pitch = numel(pitch_bp);
    n_roll  = numel(roll_bp);

    % Use level-attitude table as reference height grid
    pi0 = find(pitch_bp == 0);
    ri0 = find(roll_bp == 0);
    ref_heights = heights_cell{pi0, ri0};
    ref_heights = ref_heights(:)';
    n_h = numel(ref_heights);

    % Build 3-D table array: (n_h x n_pitch x n_roll)
    table_3d = zeros(n_h, n_pitch, n_roll);

    for pi = 1:n_pitch
        for ri = 1:n_roll
            h_raw = heights_cell{pi, ri}; h_raw = h_raw(:)';
            v_raw = volumes_cell{pi, ri}; v_raw = v_raw(:)';

            if numel(h_raw) == n_h && all(abs(h_raw - ref_heights) < 0.01)
                table_3d(:, pi, ri) = v_raw;
            else
                table_3d(:, pi, ri) = interp1(h_raw, v_raw, ref_heights, ...
                    'linear', 'extrap');
            end
        end
    end

    % Enforce monotonicity
    for pi = 1:n_pitch
        for ri = 1:n_roll
            col = table_3d(:, pi, ri);
            for k = 2:n_h
                if col(k) < col(k-1)
                    col(k) = col(k-1);
                end
            end
            table_3d(:, pi, ri) = col;
        end
    end
    table_3d = max(0, table_3d);

    lut = Simulink.LookupTable;
    lut.Table.Value = table_3d;
    lut.Table.DataType = 'double';
    lut.Breakpoints(1).Value = ref_heights;
    lut.Breakpoints(1).DataType = 'double';
    lut.Breakpoints(2).Value = pitch_bp;
    lut.Breakpoints(2).DataType = 'double';
    lut.Breakpoints(3).Value = roll_bp;
    lut.Breakpoints(3).DataType = 'double';
    lut.StructTypeInfo.Name = sprintf('LUT_%s_Type', prefix);

    lut_name = sprintf('LUT_%s', prefix);
    addOrUpdateDD(ddata, lut_name, lut);

    fprintf('  %s: %dx%dx%d = %d entries (height: [%.1f, %.1f])\n', ...
        lut_name, n_h, n_pitch, n_roll, numel(table_3d), ...
        ref_heights(1), ref_heights(end));
end

saveChanges(dd);
close(dd);

fprintf('\n  Step 2 complete. Data dictionary saved.\n\n');

%% ========================================================================
%  STEP 3: BUILD SIMULINK MODELS
%  ========================================================================

fprintf('================================================================\n');
fprintf('  STEP 3: BUILD SIMULINK MODELS\n');
fprintf('================================================================\n\n');

% Ensure models and data dirs are on path
addpath(model_dir);
addpath(dd_dir);

% --- 3a. ProbeModel_Real ---
% Models a single capacitance probe (used for T1, T2, T4).
%
% Signal flow:
%   fuel_wl (WL at probe, inches)
%     --> Subtract probe_base_wl --> raw height above probe base
%     --> Clamp to [0, active_length] --> physical wetted height
%     --> Add band-limited white noise (sigma=0.02", Cov=0.0004)
%     --> probe_height (output, inches)
%
%   fuel_wl also passes through directly to fuel_wl_at_probe (for logging)
%
% The "Saturation Dynamic" block clamps the probe reading between zero
% (probe fully dry) and the active length (probe fully submerged).
% Real probes cannot report negative heights or heights beyond their length.
%
% Model workspace defaults are for T1 (FS 210). When instantiated in the
% top-level model for T2 or T4, these values would be overridden.
fprintf('Building ProbeModel_Real...\n');
mdl = createModel('ProbeModel_Real', model_dir, dd_path);

mdlWS = get_param(mdl, 'ModelWorkspace');
assignin(mdlWS, 'probe_base_wl', 88.24);   % T1 probe base waterline (inches)
assignin(mdlWS, 'probe_top_wl', 103.68);    % T1 probe top waterline (inches)

add_block('simulink/Sources/In1', [mdl '/fuel_wl'], ...
    'Position', [30 80 60 100], 'Port', '1');
add_block('simulink/Sinks/Out1', [mdl '/probe_height'], ...
    'Position', [550 80 580 100], 'Port', '1');
add_block('simulink/Sinks/Out1', [mdl '/fuel_wl_at_probe'], ...
    'Position', [550 140 580 160], 'Port', '2');

% Subtract probe base WL
add_block('simulink/Math Operations/Add', [mdl '/SubBase'], ...
    'Position', [140 75 180 105], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/BaseWL'], ...
    'Value', 'probe_base_wl', 'Position', [60 120 110 140]);

% Active length = top - base
add_block('simulink/Math Operations/Add', [mdl '/ActiveLen'], ...
    'Position', [140 170 180 200], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/TopWL'], ...
    'Value', 'probe_top_wl', 'Position', [60 170 110 190]);
add_block('simulink/Sources/Constant', [mdl '/BaseWL2'], ...
    'Value', 'probe_base_wl', 'Position', [60 210 110 230]);

% Clamp to [0, active_length]
add_block('simulink/Discontinuities/Saturation Dynamic', [mdl '/Clamp'], ...
    'Position', [260 60 320 120]);
add_block('simulink/Sources/Constant', [mdl '/Zero'], ...
    'Value', '0', 'Position', [180 40 210 60]);

% Probe noise
add_block('simulink/Sources/Band-Limited White Noise', [mdl '/Noise'], ...
    'Cov', '0.0004', 'Ts', '0.1', 'seed', '[23341]', ...
    'Position', [260 140 310 170]);
add_block('simulink/Math Operations/Add', [mdl '/AddNoise'], ...
    'Position', [380 75 420 105]);

% Wire
add_line(mdl, 'fuel_wl/1', 'SubBase/1', 'autorouting', 'smart');
add_line(mdl, 'BaseWL/1', 'SubBase/2', 'autorouting', 'smart');
add_line(mdl, 'TopWL/1', 'ActiveLen/1', 'autorouting', 'smart');
add_line(mdl, 'BaseWL2/1', 'ActiveLen/2', 'autorouting', 'smart');
add_line(mdl, 'Zero/1', 'Clamp/1', 'autorouting', 'smart');
add_line(mdl, 'SubBase/1', 'Clamp/2', 'autorouting', 'smart');
add_line(mdl, 'ActiveLen/1', 'Clamp/3', 'autorouting', 'smart');
add_line(mdl, 'Clamp/1', 'AddNoise/1', 'autorouting', 'smart');
add_line(mdl, 'Noise/1', 'AddNoise/2', 'autorouting', 'smart');
add_line(mdl, 'AddNoise/1', 'probe_height/1', 'autorouting', 'smart');
add_line(mdl, 'fuel_wl/1', 'fuel_wl_at_probe/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

% --- 3b. ProbeModel_Combo ---
% Models T3's dual-probe arrangement with a blend zone.
%
% T3 (Center/Collector) has two probes with overlapping ranges:
%   Lower probe: WL 80.30 to 92.00 (covers bottom of tank)
%   Upper probe: WL 90.00 to 99.60 (covers top of tank)
%   Overlap/blend zone: WL 90.0 to 92.0
%
% Signal flow:
%   fuel_wl --> Lower probe height: clamp(fuel_wl - 80.30, 0, 11.70)
%          --> Upper probe height: clamp(fuel_wl - 90.00, 0, 9.60)
%          --> Blend weight: w = clamp((fuel_wl - 90) / 2, 0, 1)
%
%   The upper probe reading is converted to lower-probe-relative coordinates:
%     upper_wl = upper_base + upper_height
%     upper_relative = upper_wl - lower_base
%
%   Blended output: h_eff = (1-w)*lower_h + w*upper_relative
%   This ensures a smooth transition across the overlap zone.
%
%   Finally, band-limited noise is added (same variance as real probe).
fprintf('Building ProbeModel_Combo...\n');
mdl = createModel('ProbeModel_Combo', model_dir, dd_path);

mdlWS = get_param(mdl, 'ModelWorkspace');
assignin(mdlWS, 'lower_base_wl', 80.30);   % Lower probe base WL
assignin(mdlWS, 'lower_top_wl', 92.00);     % Lower probe top WL
assignin(mdlWS, 'upper_base_wl', 90.00);    % Upper probe base WL
assignin(mdlWS, 'upper_top_wl', 99.60);     % Upper probe top WL
assignin(mdlWS, 'blend_lo', 90.0);          % Blend zone start (WL)
assignin(mdlWS, 'blend_hi', 92.0);          % Blend zone end (WL)

add_block('simulink/Sources/In1', [mdl '/fuel_wl'], ...
    'Position', [30 100 60 120]);
add_block('simulink/Sinks/Out1', [mdl '/probe_height'], ...
    'Position', [700 100 730 120]);

% Lower probe height
add_block('simulink/Math Operations/Add', [mdl '/LowerSub'], ...
    'Position', [120 50 160 80], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/LowerBase'], ...
    'Value', 'lower_base_wl', 'Position', [40 85 90 105]);
add_block('simulink/Discontinuities/Saturation', [mdl '/LowerClamp'], ...
    'UpperLimit', 'lower_top_wl - lower_base_wl', 'LowerLimit', '0', ...
    'Position', [200 50 260 80]);

% Upper probe height
add_block('simulink/Math Operations/Add', [mdl '/UpperSub'], ...
    'Position', [120 140 160 170], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/UpperBase'], ...
    'Value', 'upper_base_wl', 'Position', [40 175 90 195]);
add_block('simulink/Discontinuities/Saturation', [mdl '/UpperClamp'], ...
    'UpperLimit', 'upper_top_wl - upper_base_wl', 'LowerLimit', '0', ...
    'Position', [200 140 260 170]);

% Blend weight
add_block('simulink/Math Operations/Add', [mdl '/BlendSub'], ...
    'Position', [120 230 160 260], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/BlendLo'], ...
    'Value', 'blend_lo', 'Position', [40 265 90 285]);
add_block('simulink/Math Operations/Gain', [mdl '/BlendScale'], ...
    'Gain', '1/(blend_hi - blend_lo)', 'Position', [200 230 260 260]);
add_block('simulink/Discontinuities/Saturation', [mdl '/BlendClampW'], ...
    'UpperLimit', '1', 'LowerLimit', '0', 'Position', [300 230 360 260]);

% Convert upper height to lower-probe-relative coordinate
add_block('simulink/Math Operations/Add', [mdl '/UpperToWL'], ...
    'Position', [300 140 340 170]);
add_block('simulink/Sources/Constant', [mdl '/UpperBaseAdd'], ...
    'Value', 'upper_base_wl', 'Position', [230 170 280 190]);
add_block('simulink/Math Operations/Add', [mdl '/UpperToRel'], ...
    'Position', [380 140 420 170], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/LowerBaseRel'], ...
    'Value', 'lower_base_wl', 'Position', [310 180 360 200]);

% Weighted blend: h_eff = (1-w)*lower_h + w*upper_h_rel
add_block('simulink/Math Operations/Product', [mdl '/ProdUpper'], ...
    'Position', [470 140 510 170]);
add_block('simulink/Math Operations/Add', [mdl '/OneMinusW'], ...
    'Position', [400 260 440 290], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/One'], ...
    'Value', '1', 'Position', [340 260 370 280]);
add_block('simulink/Math Operations/Product', [mdl '/ProdLower'], ...
    'Position', [470 50 510 80]);
add_block('simulink/Math Operations/Add', [mdl '/BlendSum'], ...
    'Position', [560 85 600 115]);

% Noise
add_block('simulink/Sources/Band-Limited White Noise', [mdl '/Noise'], ...
    'Cov', '0.0004', 'Ts', '0.1', 'seed', '[44721]', ...
    'Position', [560 130 610 160]);
add_block('simulink/Math Operations/Add', [mdl '/AddNoise'], ...
    'Position', [650 90 690 120]);

% Wire
add_line(mdl, 'fuel_wl/1', 'LowerSub/1', 'autorouting', 'smart');
add_line(mdl, 'LowerBase/1', 'LowerSub/2', 'autorouting', 'smart');
add_line(mdl, 'LowerSub/1', 'LowerClamp/1', 'autorouting', 'smart');
add_line(mdl, 'fuel_wl/1', 'UpperSub/1', 'autorouting', 'smart');
add_line(mdl, 'UpperBase/1', 'UpperSub/2', 'autorouting', 'smart');
add_line(mdl, 'UpperSub/1', 'UpperClamp/1', 'autorouting', 'smart');
add_line(mdl, 'UpperClamp/1', 'UpperToWL/1', 'autorouting', 'smart');
add_line(mdl, 'UpperBaseAdd/1', 'UpperToWL/2', 'autorouting', 'smart');
add_line(mdl, 'UpperToWL/1', 'UpperToRel/1', 'autorouting', 'smart');
add_line(mdl, 'LowerBaseRel/1', 'UpperToRel/2', 'autorouting', 'smart');
add_line(mdl, 'fuel_wl/1', 'BlendSub/1', 'autorouting', 'smart');
add_line(mdl, 'BlendLo/1', 'BlendSub/2', 'autorouting', 'smart');
add_line(mdl, 'BlendSub/1', 'BlendScale/1', 'autorouting', 'smart');
add_line(mdl, 'BlendScale/1', 'BlendClampW/1', 'autorouting', 'smart');
add_line(mdl, 'UpperToRel/1', 'ProdUpper/1', 'autorouting', 'smart');
add_line(mdl, 'BlendClampW/1', 'ProdUpper/2', 'autorouting', 'smart');
add_line(mdl, 'One/1', 'OneMinusW/1', 'autorouting', 'smart');
add_line(mdl, 'BlendClampW/1', 'OneMinusW/2', 'autorouting', 'smart');
add_line(mdl, 'LowerClamp/1', 'ProdLower/1', 'autorouting', 'smart');
add_line(mdl, 'OneMinusW/1', 'ProdLower/2', 'autorouting', 'smart');
add_line(mdl, 'ProdLower/1', 'BlendSum/1', 'autorouting', 'smart');
add_line(mdl, 'ProdUpper/1', 'BlendSum/2', 'autorouting', 'smart');
add_line(mdl, 'BlendSum/1', 'AddNoise/1', 'autorouting', 'smart');
add_line(mdl, 'Noise/1', 'AddNoise/2', 'autorouting', 'smart');
add_line(mdl, 'AddNoise/1', 'probe_height/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

% --- 3c. ProbeModel_Pseudo ---
% Models T5 which has no physical probe. Instead, the fuel height is
% PROJECTED from T3's probe reading using the aircraft attitude.
%
% Physics: If T3's probe reads height h at location (fs_t3, bl_t3), then
% the fuel surface at T5's location (offset by dx=55" aft, dy=0") is:
%   h_T5 = h_T3 + dx*tan(pitch) + dy*tan(roll)
%
% The floor offset accounts for the difference in tank floor elevations:
%   T3 floor = WL 80.30 (probe base), T5 floor = WL 83.0
%   So we subtract (83.0 - 80.30) = 2.70" from the projected height.
%
% The result is clamped to [0, tank_height] since fuel cannot be negative
% or exceed the T5 tank ceiling.
%
% This is an inherently less accurate measurement method because:
%   - Small pitch errors are amplified by the 55" FS offset
%   - No direct measurement of T5 fuel level
%   - Assumes a planar fuel surface connecting T3 and T5
fprintf('Building ProbeModel_Pseudo...\n');
mdl = createModel('ProbeModel_Pseudo', model_dir, dd_path);

mdlWS = get_param(mdl, 'ModelWorkspace');
assignin(mdlWS, 'pseudo_dx', 55.0);       % FS offset from T3 (inches aft)
assignin(mdlWS, 'pseudo_dy', 0.0);        % BL offset from T3 (inches right)
assignin(mdlWS, 'tank_wl_min', 83.0);     % T5 floor waterline
assignin(mdlWS, 'tank_height', 22.0);     % T5 height (WL 83 to 105)

add_block('simulink/Sources/In1', [mdl '/t3_height'], ...
    'Position', [30 50 60 70], 'Port', '1');
add_block('simulink/Sources/In1', [mdl '/pitch_deg'], ...
    'Position', [30 120 60 140], 'Port', '2');
add_block('simulink/Sources/In1', [mdl '/roll_deg'], ...
    'Position', [30 190 60 210], 'Port', '3');
add_block('simulink/Sinks/Out1', [mdl '/probe_height'], ...
    'Position', [600 80 630 100]);

% Pitch path: dx * tan(pitch_rad)
add_block('simulink/Math Operations/Gain', [mdl '/DegToRadP'], ...
    'Gain', 'pi/180', 'Position', [120 115 160 145]);
add_block('simulink/Math Operations/Trigonometric Function', [mdl '/TanP'], ...
    'Function', 'tan', 'Position', [200 115 240 145]);
add_block('simulink/Math Operations/Gain', [mdl '/GainDx'], ...
    'Gain', 'pseudo_dx', 'Position', [280 115 330 145]);

% Roll path: dy * tan(roll_rad)
add_block('simulink/Math Operations/Gain', [mdl '/DegToRadR'], ...
    'Gain', 'pi/180', 'Position', [120 185 160 215]);
add_block('simulink/Math Operations/Trigonometric Function', [mdl '/TanR'], ...
    'Function', 'tan', 'Position', [200 185 240 215]);
add_block('simulink/Math Operations/Gain', [mdl '/GainDy'], ...
    'Gain', 'pseudo_dy', 'Position', [280 185 330 215]);

% Sum: t3_height + dx*tan(pitch) + dy*tan(roll)
add_block('simulink/Math Operations/Add', [mdl '/SumProj'], ...
    'Position', [400 60 440 120], 'Inputs', '+++');

% Floor offset: projected_WL - T5_wl_min
add_block('simulink/Math Operations/Add', [mdl '/SubFloor'], ...
    'Position', [480 70 520 100], 'Inputs', '+-');
add_block('simulink/Sources/Constant', [mdl '/FloorOffset'], ...
    'Value', 'tank_wl_min - 80.30', 'Position', [420 130 470 150]);

% Clamp to [0, tank_height]
add_block('simulink/Discontinuities/Saturation', [mdl '/ClampT5'], ...
    'UpperLimit', 'tank_height', 'LowerLimit', '0', ...
    'Position', [550 70 600 100]);

add_line(mdl, 'pitch_deg/1', 'DegToRadP/1', 'autorouting', 'smart');
add_line(mdl, 'DegToRadP/1', 'TanP/1', 'autorouting', 'smart');
add_line(mdl, 'TanP/1', 'GainDx/1', 'autorouting', 'smart');
add_line(mdl, 'roll_deg/1', 'DegToRadR/1', 'autorouting', 'smart');
add_line(mdl, 'DegToRadR/1', 'TanR/1', 'autorouting', 'smart');
add_line(mdl, 'TanR/1', 'GainDy/1', 'autorouting', 'smart');
add_line(mdl, 't3_height/1', 'SumProj/1', 'autorouting', 'smart');
add_line(mdl, 'GainDx/1', 'SumProj/2', 'autorouting', 'smart');
add_line(mdl, 'GainDy/1', 'SumProj/3', 'autorouting', 'smart');
add_line(mdl, 'SumProj/1', 'SubFloor/1', 'autorouting', 'smart');
add_line(mdl, 'FloorOffset/1', 'SubFloor/2', 'autorouting', 'smart');
add_line(mdl, 'SubFloor/1', 'ClampT5/1', 'autorouting', 'smart');
add_line(mdl, 'ClampT5/1', 'probe_height/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

% --- 3d. ProbeFailureDetector ---
% Monitors probe readings for three failure modes and holds the Last
% Known Good (LKG) value when a fault is detected.
%
% Failure checks:
%   1. Open circuit:  reading < -0.1" (probe disconnected, reads below zero)
%   2. Short circuit: reading > max_height + 0.5" (electrodes shorted, reads full scale)
%   3. Rate exceed:   |dh/dt| > 2.0 in/s (physically impossible rate of change)
%
% When any fault is detected:
%   - The OR gate fires
%   - The Switch block selects the LKG value (from Memory block) instead of raw
%   - The LKG Memory block holds the last valid reading
%   - is_failed output goes True
%   - failure_code output reflects which fault type
%
% When no faults are present:
%   - The Switch passes through the raw reading
%   - The LKG Memory continuously updates with the current valid reading
%
% The Memory block introduces one sample of delay, which is acceptable
% for the slowly-varying fuel levels in this system.
fprintf('Building ProbeFailureDetector...\n');
mdl = createModel('ProbeFailureDetector', model_dir, dd_path);

mdlWS = get_param(mdl, 'ModelWorkspace');
assignin(mdlWS, 'max_probe_height', 15.44);  % T1 active length (default)

add_block('simulink/Sources/In1', [mdl '/raw_height'], ...
    'Position', [30 100 60 120]);
add_block('simulink/Sinks/Out1', [mdl '/valid_height'], ...
    'Position', [650 100 680 120]);
add_block('simulink/Sinks/Out1', [mdl '/is_failed'], ...
    'Position', [650 200 680 220], 'Port', '2');
add_block('simulink/Sinks/Out1', [mdl '/failure_code'], ...
    'Position', [650 280 680 300], 'Port', '3');

% Memory for previous reading
add_block('simulink/Discrete/Memory', [mdl '/PrevReading'], ...
    'Position', [120 160 160 180]);

% Rate of change
add_block('simulink/Math Operations/Add', [mdl '/Diff'], ...
    'Position', [200 100 240 140], 'Inputs', '+-');
add_block('simulink/Math Operations/Abs', [mdl '/AbsRate'], ...
    'Position', [270 100 310 130]);

% Open circuit: raw < FAILURE_OPEN_THRESH
add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [mdl '/OpenCkt'], 'const', 'FAILURE_OPEN_THRESH', 'relop', '<', ...
    'Position', [200 220 270 250]);

% Short circuit: raw > max + margin
add_block('simulink/Math Operations/Add', [mdl '/ShortThresh'], ...
    'Position', [140 270 180 300], 'Inputs', '++');
add_block('simulink/Sources/Constant', [mdl '/MaxH'], ...
    'Value', 'max_probe_height', 'Position', [60 260 100 280]);
add_block('simulink/Sources/Constant', [mdl '/ShortMargin'], ...
    'Value', 'FAILURE_SHORT_MARGIN', 'Position', [60 300 100 320]);
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [mdl '/ShortCkt'], 'Operator', '>', 'Position', [240 270 280 300]);

% Rate exceedance
add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [mdl '/RateExceed'], 'const', 'FAILURE_RATE_THRESH', 'relop', '>', ...
    'Position', [340 100 410 130]);

% OR gate
add_block('simulink/Logic and Bit Operations/Logical Operator', [mdl '/FaultOR'], ...
    'Operator', 'OR', 'Inputs', '3', 'Position', [440 160 480 240]);

% Switch: raw if healthy, LKG if failed
add_block('simulink/Discrete/Memory', [mdl '/LKG_Memory'], ...
    'Position', [500 60 540 80]);
add_block('simulink/Signal Routing/Switch', [mdl '/FaultSwitch'], ...
    'Criteria', 'u2 > Threshold', 'Threshold', '0.5', ...
    'Position', [560 80 600 130]);

% Wire
add_line(mdl, 'raw_height/1', 'PrevReading/1', 'autorouting', 'smart');
add_line(mdl, 'raw_height/1', 'Diff/1', 'autorouting', 'smart');
add_line(mdl, 'PrevReading/1', 'Diff/2', 'autorouting', 'smart');
add_line(mdl, 'Diff/1', 'AbsRate/1', 'autorouting', 'smart');
add_line(mdl, 'AbsRate/1', 'RateExceed/1', 'autorouting', 'smart');
add_line(mdl, 'raw_height/1', 'OpenCkt/1', 'autorouting', 'smart');
add_line(mdl, 'MaxH/1', 'ShortThresh/1', 'autorouting', 'smart');
add_line(mdl, 'ShortMargin/1', 'ShortThresh/2', 'autorouting', 'smart');
add_line(mdl, 'raw_height/1', 'ShortCkt/1', 'autorouting', 'smart');
add_line(mdl, 'ShortThresh/1', 'ShortCkt/2', 'autorouting', 'smart');
add_line(mdl, 'OpenCkt/1', 'FaultOR/1', 'autorouting', 'smart');
add_line(mdl, 'ShortCkt/1', 'FaultOR/2', 'autorouting', 'smart');
add_line(mdl, 'RateExceed/1', 'FaultOR/3', 'autorouting', 'smart');
add_line(mdl, 'raw_height/1', 'FaultSwitch/1', 'autorouting', 'smart');
add_line(mdl, 'FaultOR/1', 'FaultSwitch/2', 'autorouting', 'smart');
add_line(mdl, 'LKG_Memory/1', 'FaultSwitch/3', 'autorouting', 'smart');
add_line(mdl, 'FaultSwitch/1', 'LKG_Memory/1', 'autorouting', 'smart');
add_line(mdl, 'FaultSwitch/1', 'valid_height/1', 'autorouting', 'smart');
add_line(mdl, 'FaultOR/1', 'is_failed/1', 'autorouting', 'smart');
add_line(mdl, 'FaultOR/1', 'failure_code/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

% --- 3e. HV_TableLookup (one per tank) ---
% Each tank gets its own HV lookup model wired to its specific LUT object
% in the data dictionary (LUT_T1 through LUT_T5).
%
% Why per-tank models instead of one parameterized model:
%   The Simulink n-D Lookup Table block's "LookupTableObject" property
%   is a string set at model build time, not a runtime parameter. You
%   cannot pass a variable string into it via model arguments. So each
%   tank needs its own .slx with the correct LUT name hardcoded.
%
% Each model takes 3 inputs and produces 1 output:
%   Inputs:  probe_height (in), pitch_deg (deg), roll_deg (deg)
%   Output:  volume_in3 (cubic inches)
%
% The n-D Lookup Table performs trilinear interpolation:
%   - Dimension 1: probe height (37-49 breakpoints, 0.5" step)
%   - Dimension 2: pitch (-6 to +6 deg, 13 breakpoints)
%   - Dimension 3: roll (-8 to +8 deg, 17 breakpoints)
%   - Interpolation: Linear point-slope
%   - Extrapolation: Clip (saturates at boundary values)
%
% A Saturation block clamps the output to [0, inf] to prevent negative
% volumes from numerical artifacts at the table boundaries.
fprintf('Building HV_TableLookup models (per-tank)...\n');

lut_names = {'LUT_T1', 'LUT_T2', 'LUT_T3', 'LUT_T4', 'LUT_T5'};
for t = 1:5
    mdl_name = sprintf('HV_TableLookup_T%d', t);
    mdl = createModel(mdl_name, model_dir, dd_path);

    add_block('simulink/Sources/In1', [mdl '/probe_height'], ...
        'Position', [30 50 60 70], 'Port', '1');
    add_block('simulink/Sources/In1', [mdl '/pitch_deg'], ...
        'Position', [30 100 60 120], 'Port', '2');
    add_block('simulink/Sources/In1', [mdl '/roll_deg'], ...
        'Position', [30 150 60 170], 'Port', '3');
    add_block('simulink/Sinks/Out1', [mdl '/volume_in3'], ...
        'Position', [400 100 430 120]);

    add_block('simulink/Lookup Tables/n-D Lookup Table', [mdl '/HV_LUT'], ...
        'Position', [200 40 300 180], ...
        'NumberOfTableDimensions', '3', ...
        'DataSpecification', 'Lookup table object', ...
        'LookupTableObject', lut_names{t}, ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');

    add_block('simulink/Discontinuities/Saturation', [mdl '/ClampVol'], ...
        'UpperLimit', 'inf', 'LowerLimit', '0', ...
        'Position', [340 90 380 120]);

    add_line(mdl, 'probe_height/1', 'HV_LUT/1', 'autorouting', 'smart');
    add_line(mdl, 'pitch_deg/1', 'HV_LUT/2', 'autorouting', 'smart');
    add_line(mdl, 'roll_deg/1', 'HV_LUT/3', 'autorouting', 'smart');
    add_line(mdl, 'HV_LUT/1', 'ClampVol/1', 'autorouting', 'smart');
    add_line(mdl, 'ClampVol/1', 'volume_in3/1', 'autorouting', 'smart');

    saveModel(mdl, model_dir);
end

% --- 3f. DensityComputation ---
% Converts the measured dielectric constant (kappa) to fuel density.
%
% The linear model is: rho = DENSITY_MODEL_A * kappa + DENSITY_MODEL_B
% For Jet-A: rho = 4.667 * kappa - 2.857 (lb/gal)
%
% At the nominal dielectric of 2.05 (60 deg F):
%   rho = 4.667 * 2.05 - 2.857 = 6.71 lb/gal (matches lab value)
%
% The 0.3% density bias (DENSITY_BIAS = 1.003) is applied as a multiplier
% to simulate a systematic calibration offset. This is one of the injected
% error sources used for validation.
%
% The output is clamped to [5.5, 8.5] lb/gal to prevent physically
% impossible density values from corrupting downstream weight calculations.
fprintf('Building DensityComputation...\n');
mdl = createModel('DensityComputation', model_dir, dd_path);

add_block('simulink/Sources/In1', [mdl '/dielectric'], ...
    'Position', [30 80 60 100]);
add_block('simulink/Sinks/Out1', [mdl '/density_lb_per_gal'], ...
    'Position', [500 80 530 100]);

% rho = DENSITY_MODEL_A * kappa + DENSITY_MODEL_B
add_block('simulink/Math Operations/Gain', [mdl '/Slope'], ...
    'Gain', 'DENSITY_MODEL_A', 'Position', [120 75 180 105]);
add_block('simulink/Math Operations/Add', [mdl '/AddIntercept'], ...
    'Position', [240 75 280 105]);
add_block('simulink/Sources/Constant', [mdl '/Intercept'], ...
    'Value', 'DENSITY_MODEL_B', 'Position', [160 120 210 140]);

% Apply density bias
add_block('simulink/Math Operations/Gain', [mdl '/BiasGain'], ...
    'Gain', 'DENSITY_BIAS', 'Position', [340 75 400 105]);

% Clamp to physical range
add_block('simulink/Discontinuities/Saturation', [mdl '/ClampDens'], ...
    'UpperLimit', '8.5', 'LowerLimit', '5.5', ...
    'Position', [440 75 480 105]);

add_line(mdl, 'dielectric/1', 'Slope/1', 'autorouting', 'smart');
add_line(mdl, 'Slope/1', 'AddIntercept/1', 'autorouting', 'smart');
add_line(mdl, 'Intercept/1', 'AddIntercept/2', 'autorouting', 'smart');
add_line(mdl, 'AddIntercept/1', 'BiasGain/1', 'autorouting', 'smart');
add_line(mdl, 'BiasGain/1', 'ClampDens/1', 'autorouting', 'smart');
add_line(mdl, 'ClampDens/1', 'density_lb_per_gal/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

% --- 3g. RefuelSystem ---
% Models the single-point refuel system with per-tank shutoff valves.
%
% In a single-point refuel system, pressurized fuel enters through one
% adapter and is distributed to all tanks via a manifold. Each tank has:
%   - A float-type high-level sensor at the max fill waterline
%   - A solenoid shutoff valve (normally open during refuel)
%
% Logic per tank:
%   valve_open = refuel_cmd AND NOT(hi_level_tripped)
%
% When the high-level sensor trips (fuel reaches max_fill_wl), that tank's
% valve closes while other tanks continue filling.
%
% The "AllFull" AND gate with 5 inputs detects when all high-level sensors
% have tripped, indicating refuel is complete.
%
% Max fill waterlines per tank:
%   T1: 103.68"  T2: 102.64"  T3: 99.60"  T4: 102.64"  T5: 104.56"
fprintf('Building RefuelSystem...\n');
mdl = createModel('RefuelSystem', model_dir, dd_path);

add_block('simulink/Sources/In1', [mdl '/refuel_cmd'], ...
    'Position', [30 30 60 50], 'Port', '1');

max_fills = [103.68, 102.64, 99.60, 102.64, 104.56];
for t = 1:5
    y = 80 + (t-1)*80;
    prefix = sprintf('T%d', t);

    add_block('simulink/Sources/In1', [mdl '/' prefix '_fuel_wl'], ...
        'Position', [30 y 60 y+20], 'Port', sprintf('%d', t+1));

    add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
        [mdl '/' prefix '_HiLevel'], ...
        'const', sprintf('%.2f', max_fills(t)), 'relop', '>=', ...
        'Position', [120 y 190 y+25]);

    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [mdl '/' prefix '_Not'], 'Operator', 'NOT', ...
        'Position', [220 y 250 y+25]);
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [mdl '/' prefix '_AND'], 'Operator', 'AND', ...
        'Position', [290 y-10 330 y+30]);

    add_block('simulink/Sinks/Out1', [mdl '/' prefix '_valve_open'], ...
        'Position', [370 y 400 y+20], 'Port', sprintf('%d', 2*t-1));
    add_block('simulink/Sinks/Out1', [mdl '/' prefix '_hi_level'], ...
        'Position', [370 y+30 400 y+50], 'Port', sprintf('%d', 2*t));

    add_line(mdl, [prefix '_fuel_wl/1'], [prefix '_HiLevel/1'], 'autorouting', 'smart');
    add_line(mdl, [prefix '_HiLevel/1'], [prefix '_Not/1'], 'autorouting', 'smart');
    add_line(mdl, 'refuel_cmd/1', [prefix '_AND/1'], 'autorouting', 'smart');
    add_line(mdl, [prefix '_Not/1'], [prefix '_AND/2'], 'autorouting', 'smart');
    add_line(mdl, [prefix '_AND/1'], [prefix '_valve_open/1'], 'autorouting', 'smart');
    add_line(mdl, [prefix '_HiLevel/1'], [prefix '_hi_level/1'], 'autorouting', 'smart');
end

% All-full detection
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [mdl '/AllFull'], 'Operator', 'AND', 'Inputs', '5', ...
    'Position', [220 470 270 530]);
add_block('simulink/Sinks/Out1', [mdl '/refuel_complete'], ...
    'Position', [310 490 340 510], 'Port', '11');

for t = 1:5
    prefix = sprintf('T%d', t);
    add_line(mdl, [prefix '_HiLevel/1'], sprintf('AllFull/%d', t), 'autorouting', 'smart');
end
add_line(mdl, 'AllFull/1', 'refuel_complete/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

% --- 3h. FuelGaugingSystem (TOP LEVEL) ---
% Integrates all sub-models into a single simulation harness.
%
% INPUT BLOCKS (Constant sources for static analysis):
%   Pitch_deg (default 0)    - Aircraft pitch angle
%   Roll_deg (default 0)     - Aircraft roll angle
%   Dielectric (KAPPA_NOMINAL=2.05) - Fuel dielectric constant
%   Refuel_Cmd (default 0)   - Refuel active flag
%   FuelWL_T1..T5            - Fuel waterline per tank (mid-tank defaults)
%
% For time-domain simulation, replace the Constant blocks with From
% Workspace blocks that read timeseries data from defuel/refuel CSVs.
%
% SIGNAL ROUTING:
%   - Pitch and Roll fan out to all 5 HV lookup models and the pseudo probe
%   - Dielectric feeds DensityComputation, whose output fans to all 5 weight blocks
%   - Each tank's processing chain is independent (parallel pipelines)
%   - All 5 weight outputs sum into TotalWeight
%
% OUTPUTS:
%   TotalWeight --> To Workspace ('total_fuel_weight' timeseries)
%   TotalWeight --> Scope (for interactive viewing)
%
% T5 NOTE: In the top-level harness, T5's pseudo probe receives FuelWL_T5
% directly as a proxy for "T3 height". In a production system, T5_Probe/1
% would be connected to T3_Probe/1 (T3's probe height output) instead.
fprintf('\nBuilding FuelGaugingSystem (top level)...\n');
mdl = createModel('FuelGaugingSystem', model_dir, dd_path);

set_param(mdl, 'SignalLogging', 'on');
set_param(mdl, 'SignalLoggingName', 'logsout');

% Inputs
add_block('simulink/Sources/Constant', [mdl '/Pitch_deg'], ...
    'Value', '0', 'Position', [30 50 80 70]);
add_block('simulink/Sources/Constant', [mdl '/Roll_deg'], ...
    'Value', '0', 'Position', [30 90 80 110]);
add_block('simulink/Sources/Constant', [mdl '/Dielectric'], ...
    'Value', 'KAPPA_NOMINAL', 'Position', [30 550 80 570]);
add_block('simulink/Sources/Constant', [mdl '/Refuel_Cmd'], ...
    'Value', '0', 'Position', [30 630 80 650]);

% Per-tank fuel WL inputs
default_wls = [96.0, 94.0, 90.0, 94.0, 94.0];
for t = 1:5
    y = 140 + (t-1)*80;
    add_block('simulink/Sources/Constant', [mdl sprintf('/FuelWL_T%d', t)], ...
        'Value', sprintf('%.1f', default_wls(t)), ...
        'Position', [30 y 80 y+20]);
end

% Density computation
add_block('simulink/Ports & Subsystems/Model', [mdl '/DensityComp'], ...
    'ModelName', 'DensityComputation', ...
    'Position', [200 540 320 580]);
add_line(mdl, 'Dielectric/1', 'DensityComp/1', 'autorouting', 'smart');

% Refuel system
add_block('simulink/Ports & Subsystems/Model', [mdl '/Refuel'], ...
    'ModelName', 'RefuelSystem', ...
    'Position', [200 620 360 720]);
add_line(mdl, 'Refuel_Cmd/1', 'Refuel/1', 'autorouting', 'smart');
for t = 1:5
    add_line(mdl, sprintf('FuelWL_T%d/1', t), sprintf('Refuel/%d', t+1), ...
        'autorouting', 'smart');
end

% Per-tank processing chain
tank_probe_models = {'ProbeModel_Real', 'ProbeModel_Real', 'ProbeModel_Combo', ...
                     'ProbeModel_Real', 'ProbeModel_Pseudo'};

% Weight summation
sum_y = 350;
add_block('simulink/Math Operations/Add', [mdl '/TotalWeight'], ...
    'Inputs', '+++++', 'Position', [800 sum_y 840 sum_y+120]);

for t = 1:5
    y = 140 + (t-1)*80;
    prefix = sprintf('T%d', t);

    % Probe model reference
    probe_mdl = tank_probe_models{t};
    add_block('simulink/Ports & Subsystems/Model', [mdl '/' prefix '_Probe'], ...
        'ModelName', probe_mdl, ...
        'Position', [200 y 320 y+50]);

    % Connect fuel WL to probe
    if t == 5
        % T5 pseudo: input is T3 probe height, pitch, roll
        % For the top-level harness with constant inputs, we feed FuelWL_T5
        % as the t3_height proxy (in a full sim this would come from T3's probe)
        add_line(mdl, sprintf('FuelWL_T%d/1', t), [prefix '_Probe/1'], ...
            'autorouting', 'smart');
        add_line(mdl, 'Pitch_deg/1', [prefix '_Probe/2'], 'autorouting', 'smart');
        add_line(mdl, 'Roll_deg/1', [prefix '_Probe/3'], 'autorouting', 'smart');
    else
        add_line(mdl, sprintf('FuelWL_T%d/1', t), [prefix '_Probe/1'], ...
            'autorouting', 'smart');
    end

    % Failure detector
    add_block('simulink/Ports & Subsystems/Model', [mdl '/' prefix '_Failure'], ...
        'ModelName', 'ProbeFailureDetector', ...
        'Position', [380 y 480 y+50]);
    add_line(mdl, [prefix '_Probe/1'], [prefix '_Failure/1'], 'autorouting', 'smart');

    % H-V table lookup (per-tank model)
    hv_mdl_name = sprintf('HV_TableLookup_T%d', t);
    add_block('simulink/Ports & Subsystems/Model', [mdl '/' prefix '_Lookup'], ...
        'ModelName', hv_mdl_name, ...
        'Position', [540 y 640 y+50]);
    add_line(mdl, [prefix '_Failure/1'], [prefix '_Lookup/1'], 'autorouting', 'smart');
    add_line(mdl, 'Pitch_deg/1', [prefix '_Lookup/2'], 'autorouting', 'smart');
    add_line(mdl, 'Roll_deg/1', [prefix '_Lookup/3'], 'autorouting', 'smart');

    % Volume to weight: weight = (volume / IN3_PER_GAL) * density
    add_block('simulink/Math Operations/Gain', [mdl '/' prefix '_ToGal'], ...
        'Gain', '1/IN3_PER_GAL', ...
        'Position', [680 y 720 y+25]);
    add_block('simulink/Math Operations/Product', [mdl '/' prefix '_Weight'], ...
        'Position', [750 y 790 y+30]);

    add_line(mdl, [prefix '_Lookup/1'], [prefix '_ToGal/1'], 'autorouting', 'smart');
    add_line(mdl, [prefix '_ToGal/1'], [prefix '_Weight/1'], 'autorouting', 'smart');
    add_line(mdl, 'DensityComp/1', [prefix '_Weight/2'], 'autorouting', 'smart');

    add_line(mdl, [prefix '_Weight/1'], sprintf('TotalWeight/%d', t), ...
        'autorouting', 'smart');
end

% Outputs
add_block('simulink/Sinks/To Workspace', [mdl '/TotalWeight_Out'], ...
    'VariableName', 'total_fuel_weight', 'SaveFormat', 'Timeseries', ...
    'Position', [880 sum_y+40 960 sum_y+70]);
add_block('simulink/Sinks/Scope', [mdl '/WeightScope'], ...
    'Position', [880 sum_y+80 920 sum_y+110]);

add_line(mdl, 'TotalWeight/1', 'TotalWeight_Out/1', 'autorouting', 'smart');
add_line(mdl, 'TotalWeight/1', 'WeightScope/1', 'autorouting', 'smart');

saveModel(mdl, model_dir);

fprintf('\n  Step 3 complete.\n\n');

%% ========================================================================
%  STEP 4: VALIDATION
%  ========================================================================

fprintf('================================================================\n');
fprintf('  STEP 4: VALIDATION\n');
fprintf('================================================================\n\n');

pass_count = 0;
fail_count = 0;

% 4a. Check model files
fprintf('--- Checking Model Files ---\n');
required_models = {
    'FuelGaugingSystem'
    'ProbeModel_Real'
    'ProbeModel_Combo'
    'ProbeModel_Pseudo'
    'ProbeFailureDetector'
    'HV_TableLookup_T1'
    'HV_TableLookup_T2'
    'HV_TableLookup_T3'
    'HV_TableLookup_T4'
    'HV_TableLookup_T5'
    'DensityComputation'
    'RefuelSystem'
};

for i = 1:numel(required_models)
    mdl_file = fullfile(model_dir, [required_models{i} '.slx']);
    if exist(mdl_file, 'file')
        fprintf('  PASS: %s.slx exists\n', required_models{i});
        pass_count = pass_count + 1;
    else
        fprintf('  FAIL: %s.slx NOT FOUND\n', required_models{i});
        fail_count = fail_count + 1;
    end
end

% 4b. Check data dictionary entries
fprintf('\n--- Checking Data Dictionary ---\n');
dd = Simulink.data.dictionary.open(dd_path);
ddata = getSection(dd, 'Design Data');

required_entries = {
    'AttitudeBus',        'Simulink.Bus'
    'ProbeReadingBus',    'Simulink.Bus'
    'TankIndicationBus',  'Simulink.Bus'
    'SystemIndicationBus','Simulink.Bus'
    'RefuelStatusBus',    'Simulink.Bus'
    'BIT_StatusBus',      'Simulink.Bus'
    'TankParams',         'Simulink.Parameter'
    'IN3_PER_GAL',        'Simulink.Parameter'
    'DENSITY_MODEL_A',    'Simulink.Parameter'
    'DENSITY_BIAS',       'Simulink.Parameter'
    'FAILURE_RATE_THRESH','Simulink.Parameter'
    'LUT_T1',            'Simulink.LookupTable'
    'LUT_T2',            'Simulink.LookupTable'
    'LUT_T3',            'Simulink.LookupTable'
    'LUT_T4',            'Simulink.LookupTable'
    'LUT_T5',            'Simulink.LookupTable'
};

for i = 1:size(required_entries, 1)
    entry_name = required_entries{i, 1};
    expected_class = required_entries{i, 2};
    try
        entry = getEntry(ddata, entry_name);
        val = getValue(entry);
        if isa(val, expected_class)
            fprintf('  PASS: %-25s (%s)\n', entry_name, expected_class);
            pass_count = pass_count + 1;
        else
            fprintf('  FAIL: %-25s wrong type: %s\n', entry_name, class(val));
            fail_count = fail_count + 1;
        end
    catch
        fprintf('  FAIL: %-25s NOT FOUND\n', entry_name);
        fail_count = fail_count + 1;
    end
end

% 4c. Check LUT dimensions
fprintf('\n--- Checking Lookup Tables ---\n');
for t = 1:5
    lut_name = sprintf('LUT_T%d', t);
    try
        entry = getEntry(ddata, lut_name);
        lut = getValue(entry);
        tbl = lut.Table.Value;
        [nh, np, nr] = size(tbl);

        if np == 13 && nr == 17
            fprintf('  PASS: %s: %dx%dx%d (height x pitch x roll)\n', lut_name, nh, np, nr);
            pass_count = pass_count + 1;
        else
            fprintf('  FAIL: %s: pitch=%d (exp 13), roll=%d (exp 17)\n', lut_name, np, nr);
            fail_count = fail_count + 1;
        end

        % Monotonicity at level attitude
        pi0 = ceil(np/2);
        ri0 = ceil(nr/2);
        col = tbl(:, pi0, ri0);
        if all(diff(col) >= -0.01)
            fprintf('  PASS: %s: monotonic at level attitude\n', lut_name);
            pass_count = pass_count + 1;
        else
            fprintf('  FAIL: %s: NOT monotonic\n', lut_name);
            fail_count = fail_count + 1;
        end
    catch ME
        fprintf('  FAIL: %s: %s\n', lut_name, ME.message);
        fail_count = fail_count + 1;
    end
end

close(dd);

% 4d. Try loading top-level model
fprintf('\n--- Checking Model Loadability ---\n');
if license('test', 'Simulink')
    for i = 1:numel(required_models)
        mdl_name = required_models{i};
        mdl_file = fullfile(model_dir, [mdl_name '.slx']);
        if exist(mdl_file, 'file')
            try
                load_system(mdl_name);
                fprintf('  PASS: %s loads successfully\n', mdl_name);
                pass_count = pass_count + 1;
                close_system(mdl_name, 0);
            catch ME
                fprintf('  FAIL: %s load error: %s\n', mdl_name, ME.message);
                fail_count = fail_count + 1;
            end
        end
    end
else
    fprintf('  SKIP: Simulink not available\n');
end

%% ========================================================================
%  SUMMARY
%  ========================================================================

fprintf('\n================================================================\n');
fprintf('  BUILD COMPLETE\n');
fprintf('================================================================\n\n');

models = dir(fullfile(model_dir, '*.slx'));
fprintf('Models created in %s:\n', model_dir);
for i = 1:numel(models)
    info = dir(fullfile(model_dir, models(i).name));
    fprintf('  %-35s %6.0f KB\n', models(i).name, info.bytes/1024);
end

fprintf('\nArchitecture:\n');
fprintf('  FuelGaugingSystem.slx (top-level harness)\n');
fprintf('    +-- DensityComputation.slx (dielectric -> density)\n');
fprintf('    +-- RefuelSystem.slx (valves + high-level sensors)\n');
fprintf('    +-- Per-tank chain x5:\n');
fprintf('        +-- ProbeModel_{Real|Combo|Pseudo}.slx\n');
fprintf('        +-- ProbeFailureDetector.slx\n');
fprintf('        +-- HV_TableLookup_T{1-5}.slx (3-D n-D LUT)\n');

fprintf('\nValidation: %d passed, %d failed\n', pass_count, fail_count);
if fail_count == 0
    fprintf('ALL CHECKS PASSED\n');
else
    fprintf('SOME CHECKS FAILED\n');
end

fprintf('\nData dictionary: %s\n', dd_path);

%% ========================================================================
%  LOCAL FUNCTIONS (must be at end of script file in MATLAB)
%  ========================================================================

function mdl = createModel(name, model_dir, dd_path)
% CREATEMODEL  Create a new Simulink model or reset an existing one.
%
%   mdl = createModel(name, model_dir, dd_path)
%
%   Creates a new model named 'name', deleting any existing .slx file
%   first. Configures the model to:
%     - Use ode23tb solver (stiff-capable, appropriate for hybrid systems)
%     - Run for 1000 seconds (covers full defuel sequence)
%     - Max step size 0.1s (10 Hz update rate, matches probe sample rate)
%     - Link to the data dictionary for all parameter resolution
%     - Return outputs to the MATLAB workspace as timeseries
    mdl = name;
    full_path = fullfile(model_dir, [name '.slx']);
    if bdIsLoaded(mdl), close_system(mdl, 0); end
    if exist(full_path, 'file'), delete(full_path); end

    new_system(mdl);
    % DataDictionary takes filename only (must be on MATLAB path)
    [~, dd_name, dd_ext] = fileparts(dd_path);
    set_param(mdl, 'DataDictionary', [dd_name dd_ext]);
    set_param(mdl, 'Solver', 'ode23tb');
    set_param(mdl, 'StopTime', '1000');
    set_param(mdl, 'MaxStep', '0.1');
    set_param(mdl, 'SaveTime', 'on');
    set_param(mdl, 'SaveOutput', 'on');
    set_param(mdl, 'ReturnWorkspaceOutputs', 'on');
end

function saveModel(mdl, model_dir)
% SAVEMODEL  Save a model to the models/ directory and close it.
    save_system(mdl, fullfile(model_dir, [mdl '.slx']));
    close_system(mdl, 0);
    fprintf('  Saved: %s.slx\n', mdl);
end

function addOrUpdateDD(section, name, value)
% ADDORUPDATEDD  Add or update an entry in a data dictionary section.
%   If the entry already exists, its value is updated in place.
%   If it doesn't exist, a new entry is created.
    try
        entry = getEntry(section, name);
        setValue(entry, value);
    catch
        addEntry(section, name, value);
    end
end
